baseURL = "https://habroptilus.github.io/"
languageCode = "en-us"
title = "Hikaru Ogura"
publishDir = "docs"

[params]
  name = "Hikaru Ogura"
  description = "ML Engineer"
  copyright = "Hikaru Ogura"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/guglilac"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/habroptilus"


[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/profile.php?id=100012186191438"


[[params.social]]
  medium = "qiita"
  icon = "search"
  link = "https://qiita.com/guglilac"


[[params.social]]
  medium = "blog"
  icon = "pencil"
  link = "https://www.smartbowwow.com/"

# parttime
[[params.parttime]]
company="DROBE Inc."
job_discription="Technical Advisor"
term="Feb 2020 - Mar 2020"

[[params.parttime]]
company="KARAKURI Inc."
job_discription="NLP, Deep Learning"
term=" Mar 2019 - Apr 2019"


[[params.parttime]]
company="SMN Corporation"
job_discription="a.i lab (R&D)"
term="Jun 2018 - Mar 2020"


#[[params.parttime]]
#company="JAPAN USEWARE SYSTEM Co.,Ltd."
#job_discription="Web developer"
#term="Aug 2017 - May 2018"

# internship

[[params.internship]]
company="Recruit Technologies Co.,Ltd."
job_discription="Data analyst course"
term="Sep 2018 - Sep 2018"


[[params.internship]]
company="Yahoo Japan Corporation"
job_discription="Data science course"
term="Aug 2018 - Aug 2018"



[[params.internship]]
company="Works Applications Co., Ltd."
job_discription="Hackathons"
term="Aug 2016 - Sep 2016"

# career

[[params.career]]
company="Yahoo Japan Corporation"
job_discription="ML engineer"
term="Apr 2020 - present"


# Product


[[params.product1]]
  title = "Tech blog"
  alt = ""
  source = "img/blog.png"
  url = "https://www.smartbowwow.com/"
  description="技術ブログ"

[[params.product1]]
  title = "Splatoon memory"
  alt = ""
  source = "img/splatoon_memory.png"
  url = "https://guglilac.pythonanywhere.com/"
  description="スプラトゥーン神経衰弱"

[[params.product1]]
  title = "Numeron app"
  alt = ""
  source = "img/numeron_app.png"
  url = "https://www.smartbowwow.com/2018/11/webnumeron-app.html"
  description="数当てゲーム"


#[[params.product1]]
#  title = "May Search"
#  alt = ""
#  source = "img/may_search1.jpg"
#  url = "javascript:void(0);"
#  description="五月祭経路探索アプリ"


[[params.product2]]
  title = "Kanji-lyric Quiz Bot"
  alt = ""
  source = "img/kanji_lyric.png"
  url = "https://twitter.com/kanji_lyric"
  description="漢字歌詞クイズbot"

[[params.product2]]
  title = "Tatsuya Fujiwara Gacha"
  alt = ""
  source = "img/tatsuya_gacha.png"
  url = "https://tatsuya-gacha.smartbowwow.com/"
  description="藤原竜也ガチャ"

[[params.product2]]
  title = "Share future"
  alt = ""
  source = "img/share_future.png"
  url = "http://app.mayfes2018-utatane.com/"
  description="未来のアイデア共有アプリ"


[[params.contributions]]
    title = "Internal Hack Day 17 report"
    media = "Yahoo! JAPAN Tech Blog"
    link = "https://techblog.yahoo.co.jp/entry/2020080430014499/"
    at  = "Aug 2020"


[[params.awards]]
  title="Internal Hack Day 17"
  content="ヤフー賞, 一休賞 受賞"
  link = "https://techblog.yahoo.co.jp/entry/2020071430011124/"
  at="Jun 2020"

[[params.awards]]
  title="Works Applications Internship"
  content="優秀賞 受賞"
  link = "https://www.worksap.co.jp/"
  at="Sep 2016"


[[params.interest]]
  item="Machine Learning"


[[params.interest]]
  item="Natural Language Processing"


[[params.interest]]
  item="Recommender System"





[[params.programming]]
  item="Python (PyTorch, Keras, Flask)"


[[params.programming]]
  item="React, HTML, CSS, Javascript"


[[params.programming]]
  item="C++, Scala, Java, Ruby, SQL"

