baseURL = "https://habroptilus.github.io/"
languageCode = "en-us"
title = "Hikaru Ogura"

publishDir = "docs"

[params]
  name = "Hikaru Ogura"
  description = "ML Engineer"
  copyright = "Hikaru Ogura"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/guglilac"


[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/habroptilus"


[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/profile.php?id=100012186191438"


[[params.social]]
  medium = "qiita"
  icon = "search"
  link = "https://qiita.com/guglilac"


[[params.social]]
  medium = "blog"
  icon = "pencil"
  link = "https://www.smartbowwow.com/"

# career

#[[params.parttime]]
#company="日本ユースウェアシステム株式会社"
#job_discription="Web developer"
#term="2017/08 - 2018/05"

[[params.parttime]]
company="ソネット・メディア・ネットワークス株式会社"
job_discription="a.i lab (R&D)"
term="2018/06 - 2020/03"


[[params.parttime]]
company="カラクリ株式会社"
job_discription="NLP, Deep Learning"
term="2019/03 - 2019/04"



[[params.parttime]]
company="株式会社DROBE"
job_discription="Technical Advisor"
term="2020/02 - 2020/03"



[[params.internship]]
company="株式会社ワークスアプリケーションズ"
job_discription="Hackathons (優秀賞受賞)"
term="2016/08 - 2016/09"


[[params.internship]]
company="ヤフー株式会社"
job_discription="data science course"
term="2018/08 -2018/08"

[[params.internship]]
company="株式会社リクルートテクノロジーズ"
job_discription="data analyst course"
term="2018/09 - 2018/09"


# Project


[[params.project1]]
  title = "Blog"
  alt = ""
  source = "img/blog.png"
  url = "https://www.smartbowwow.com/"
  description="技術ブログ"

[[params.project1]]
  title = "Numeron app"
  alt = ""
  source = "img/numeron_app.png"
  url = "https://www.smartbowwow.com/2018/11/webnumeron-app.html"
  description="数当てゲーム"



#[[params.project1]]
#  title = "May Search"
#  alt = ""
#  source = "img/may_search1.jpg"
#  url = "javascript:void(0);"
#  description="五月祭経路探索アプリ"


[[params.project2]]
  title = "Tatsuya Fujiwara Gacha"
  alt = ""
  source = "img/tatsuya_gacha.png"
  url = "https://tatsuya-gacha.smartbowwow.com/"
  description="藤原竜也ガチャ"

[[params.project2]]
  title = "Kanji-lyric Quiz Bot"
  alt = ""
  source = "img/kanji_lyric.png"
  url = "https://twitter.com/kanji_lyric"
  description="漢字歌詞クイズbot"



[[params.project2]]
  title = "Share future"
  alt = ""
  source = "img/share_future.png"
  url = "http://app.mayfes2018-utatane.com/"
  description="未来のアイデア共有アプリ"



[[params.interest]]
  item="Machine Learning"


[[params.interest]]
  item="Natural Language Processing"


[[params.interest]]
  item="Recommender System"





[[params.programming]]
  item="Python (PyTorch, Keras, Flask)"


[[params.programming]]
  item="React, HTML, CSS, Javascript"


[[params.programming]]
  item="C++, Scala, Java, Ruby, SQL"

